config/routes.rb
Rails.application.routes.draw do

  root 'bros#home'
  get 'about', to: 'bros#about'
  get 'motivation', to: 'bros#motivation'

end

app/models/bro.rb
class Bro < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bros_controller.rb
class BrosController < ApplicationController
  def about
		
  end
  def home
  	
  end

  def motivation
	
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bros_helper.rb
module BrosHelper
end

app/views/bros/_footer.html.erb
	<footer id="footer">
		<div class="wrapper">
			
			<div class="contact-info">
				<h3 class="title">Barbrothers Taiwan</h3>
				<div class="address">
					No.1, Sec. 2, Xinsheng S. Rd.<br />
					Da'an Dist., Taipei City 1065<br />
					Taiwan (R.O.C.)
				</div>
				
				<a href="mailto:BarbrothersTaiwan@gmail.com">BarbrothersTaiwan@gmail.com</a>
			</div>
			
			<div class="navigation">
				<h3 class="title">navigate</h3>
				<ul>
					<li><%= link_to "about",about_path  %></li>
					<li><%= link_to "forum",root_path  %></li>
					<li><%= link_to "motivation",motivation_path  %></li>
				</ul>
			</div>
			
			<div class="laboratory">
				<h3 class="title">laboratory</h3>
				<ul>
					<li><%= link_to "style guide",root_path  %></li>
					<li><%= link_to "bark PR",root_path  %></li>
					<li><%= link_to "keep SA Real",root_path  %></li>
				</ul>
			</div>
			
			<div class="social-media">
				<ul>
					<li>
						<a href="https://www.youtube.com/channel/UCHlWZQYsWzy0qKjM76XygPw/playlists" target="_blank">
							<i class="icon-youtube"></i>
						</a>
					</li>
					<li>
						<a href="http://websta.me/n/barbrothersdc" target="_blank">
							<i class="icon-instagramm"></i>
						</a>
					</li>
					<li>
						<a href="https://twitter.com/barbrothers_dc" target="_blank">
							<i class="icon-twitter-squared"></i>
						</a>
					</li>
					<li>
						<a href="https://www.facebook.com/BarBrothersTaiwan" target="_blank">
							<i class="icon-facebook"></i>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</footer>
	
	
	<div class="loading-bar"></div>

app/views/bros/_header.html.erb
	<header id="header">
		<div class="wrapper">
			
			<div class="branding">
				<div class="logo">
					<%= link_to image_tag("barbrotherTaiwan_logo.png"),root_path  %>
				</div>
				<div class="tagline">
					<div class="subtitle">Power. Balance. Strength.</div>
					<div class="title">We are BarBrothers.</div>
				</div>
			</div>
			
			<nav id="navigation">
				<ul>
					<li>
						<%= link_to "about",about_path  %>				
					</li>
					<li>
						<%= link_to "forum",root_path  %>
					</li>
					<li>
						<%= link_to "motivation",motivation_path  %>
					</li>
					<li>
						<%= link_to "sign in",root_path  %>				
					</li>
				</ul>
			</nav>
			
		</div>
    </header>

app/views/bros/about.html.erb
  <div class="loading-bar"></div>

	<%= render 'header' %>

	<%= render 'footer' %>

app/views/bros/home.html.erb
  <div class="loading-bar"></div>

  <div id="loading-mask">
   	<%= image_tag "be_the_best_you_can_be.png" %>
  </div> 

	<%= render 'header' %>


<video autoplay muted poster="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/polina.jpg" id="bgvid" loop>
  <!-- WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the "Pause" button  -->
<source src="chris.webm" type="video/webm">
<source src="barbrothers.mp4" type="video/mp4">
</video>

<div class="img-responsive" alt="Responsive image"
	width: 100%; height: auto; >
	<%= image_tag("home_pic.png")	 %>
</div>

<div id="polina">
	<h1>BarBrothers Taiwan</h1>
	<p>Founded by Kevin 2014
	<!-- <a href="">original article</a> -->
	<p>BAR BROTHERS is a calisthenic workout team that performs creative body weight exercises to obtain strength! These types of workouts are efficient, fun, and the cheapest way to get a great body! </p>
	<p>Our goal is to MOTIVATE you to get in shape and help you reach your life goals! Join our worldwide movement, choose a healthy lifestyle, and let us build your fundamentals to greatness!</p>
	<p>Join our worldwide Family today! More Info and Workouts!</p>
	<button>Pause</button>
</div>

	<%= render 'footer' %>

app/views/bros/motivation.html.erb
  <div class="loading-bar"></div>

	<%= render 'header' %>
	
	<main id="content">
		<div class="wrapper">
			
			<div id="works-intro">

				<!-- 第一層 左右平分 -->
				<div class="work half-width left">
					<%= image_tag "lazar6.png" %>
				</div>

				<div class="work half-width right">
					<img src="http://placehold.it/1200x1200" alt="Written" />
					<a href="https://www.youtube.com/watch?v=VdBbtLQHPCg" target="_blank">
						<div class="caption">
							<!-- <h2 class="title"></h2> -->
							<div class="subtitle big">Today is your day, <br>
							To start fresh. <br> To eat right. <br> To train hard. <br> To live healthy. <br> To be Proud.
							</div>
						</div>
					</a>
				</div>

				<!-- 第二層 -->	

				<div class="work two-third-width left">
					<img src="http://placehold.it/660x330" alt="Codeup" />
					<a href="https://www.youtube.com/watch?v=BK5seVTgfRE" target="_blank">
						<div class="caption">
							<!-- <h2 class="title"></h2> -->
							<div class="subtitle">
								Some people want it to happen, <br> some wish it would happen, <br>others make it happen.
							</div>
						</div>
					</a>
				</div>		

				<div class="work one-third-width right">
					<%= image_tag "lazar2.png" %>
				</div>

				<!-- 第三層 -->	
				<div class="work three-one-third-width left">
					<img src="http://placehold.it/1200x1200" alt="Codeup" />
					<a href="https://www.youtube.com/watch?v=x3wCNVAvJEw" target="_blank">
						<div class="caption">
							<!-- <h2 class="title"></h2> -->
							<div class="subtitle">Be the best you can be. </div>
						</div>
					</a>
				</div>

				<div class="work three-one-third-width middle">
					<%= image_tag "lazar3.png" %>
				</div>			

				<div class="work three-one-third-width right">
					<img src="http://placehold.it/1200x1200" alt="Ecamm" />
					<a href="https://www.youtube.com/watch?v=TrCTLLF02Lo" target="_blank">
						<div class="caption">
							<!-- <h2 class="title"></h2> -->
						<div class="subtitle">Go hard or Go home.</div>
						</div>
					</a>
				</div>
				<!-- 第四層 -->	
				<div class="work one-third-width left">
					<%= image_tag "Dusan_Djolevic2.png" %>
				</div>

				<div class="work two-third-width right">
					<img src="http://placehold.it/660x330" alt="Codeup" />
					<a href="https://www.youtube.com/watch?v=BK5seVTgfRE" target="_blank">
						<div class="caption">
							<!-- <h2 class="title"></h2> -->
							<div class="subtitle">It always seems impossible until it's done.
							</div>
						</div>
					</a>
				</div>		

				<!-- 最後一層 -->	

				<div class="work half-width left">
					<img src="http://placehold.it/1200x1200" alt="Written" />
					<a href="https://www.youtube.com/watch?v=VdBbtLQHPCg" target="_blank">
						<div class="caption">
							<!-- <h2 class="title"></h2> -->
							<div class="subtitle big">
							I don't believe you have to <br> be better than everybody else. <br> I believe you have to be better than <br> you ever thought you could be.
							</div>
						</div>
					</a>
				</div>

				<div class="work half-width right">
					<%= image_tag "lazar8.png" %>
				</div>


				</div>
			</div>
	</main>
	
	<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BarbrothersTaiwan</title>
  	<meta charset="UTF-8" />
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>


</head>

<body>

	<%= yield %>

</body>
</html>